AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for CloudFront distribution with ACM certificate

Resources:
  PrimaryBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "www.avautismcenter.com"
      WebsiteConfiguration:
        IndexDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
        IgnorePublicAcls: false

  PrimaryBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref PrimaryBucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::www.avautismcenter.com/*"
            Principal: "*"

  RedirectBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "antelopevalleyautismcenter.com"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: "avautismcenter.com"
          Protocol: "https"

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: "S3Origin"
            DomainName: !GetAtt PrimaryBucket.RegionalDomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods:
            - "GET"
            - "HEAD"
          CachedMethods:
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:560888333536:certificate/eb2ec7a1-007e-4589-8a74-ae80c349fb68"
          SslSupportMethod: "sni-only"
        Aliases:
          - "avautismcenter.com"
          - "www.avautismcenter.com"
        DefaultRootObject: "index.html"

Outputs:
  PrimaryBucketName:
    Description: "Name of the primary S3 bucket"
    Value: !Ref PrimaryBucket

  RedirectBucketName:
    Description: "Name of the redirect S3 bucket"
    Value: !Ref RedirectBucket

  CloudFrontDomainName:
    Description: "Domain name of the CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName

