name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path of the file to deploy'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Update with your S3 region

      # Step 4: Sync the Specific File to S3
      - name: Deploy File to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          if [ -z "${{ github.event.inputs.file_path }}" ]; then
            echo "File path not provided. Exiting."
            exit 1
          fi
          echo "Syncing file ${{ github.event.inputs.file_path }} to S3 bucket: $S3_BUCKET"
          aws s3 cp ${{ github.event.inputs.file_path }} s3://${S3_BUCKET}/${{ github.event.inputs.file_path }}

      # Step 5: Invalidate the Specific File in CloudFront
      - name: Invalidate CloudFront Cache
        env:
          CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          if [ -z "${{ github.event.inputs.file_path }}" ]; then
            echo "File path not provided. Exiting."
            exit 1
          fi
          echo "Invalidating CloudFront cache for file: ${{ github.event.inputs.file_path }}"
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/${{ github.event.inputs.file_path }}"

